import Head from "next/head";
import Dashboard from "@/components/Dashboard/Dashboard";
import HelloUser from "@/components/HelloUser/HelloUser";
import Feedback from "@/components/Feedback/Feedback";

export default function Home() {
  return (
    <>
      <Head>
        <title>Orb Training</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HelloUser></HelloUser>
      <Dashboard></Dashboard>
      <Feedback></Feedback>
    </>
  );
}
